# Generated by Django 3.0.7 on 2020-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200725_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
