# Generated by Django 3.0.7 on 2020-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200725_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(choices=[('Net Banking', 'Net Banking'), ('Cash on Delivery', 'Cash on Delivery'), ('Card Payment', 'Card Payment')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
