# Generated by Django 3.0.7 on 2020-07-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
